extends SceneTree

const Recorder=preload("res://scripts/playtest_recorder.gd")
var checks=0
var failures=[]
func check(ok: bool,label: String):
	checks+=1;print("PASS " if ok else "FAIL ",label)
	if not ok:failures.append(label)
func _initialize():call_deferred("run")
func run():
	var r=Recorder.new()
	r.configure({"run_id":"recorder-test","mode":"campaign"})
	check(not r.enabled and not r.record(3,"locked","travel","ignored"),"Recording is disabled by default")
	check(r.events.is_empty() and r.sequence==0 and not r.write_report("user://must-not-write.json"),"Disabled recorder retains no events and writes nothing")
	r.configure({"run_id":"recorder-test","source_hash":"fixture","mode":"campaign","seed":"test","tuning_revision":"unchanged"},true,16)
	var payload={"before":10,"after":8,"nested":{"items":["scrap"]}}
	check(r.record(3,"locked","construction","resource_transaction",payload),"Committed transaction can be recorded")
	payload.nested.items.append("changed")
	check(r.events[0].payload.nested.items==["scrap"],"Retained payload is detached from mutable callers")
	r.sample_state(3,"locked","travel",{"aboard":true})
	var count=r.events.size()
	r.sample_state(8,"locked","travel",{"aboard":true})
	check(r.events.size()==count,"Identical state samples coalesce")
	r.sample_state(8,"locked","travel",{"distance":100})
	check(r.events.size()==count,"Changing resource flags cannot spam state transitions")
	r.sample_state(8,"locked","menu")
	r.sample_state(8,"locked","menu")
	var view=r.snapshot(8)
	check(is_equal_approx(view.dwell.travel.simulation_s,5) and view.dwell.menu.simulation_s==0,"Paused menu time does not invent simulation time")
	view.events.clear();view.dwell.travel.simulation_s=999
	check(r.events.size()==3 and r.dwell.travel.simulation_s==5,"Snapshot cannot mutate internal events or dwell totals")
	r.begin_segment({"mode":"checkpoint","checkpoint_id":"defense","seed":"playtest-defense"},0)
	r.sample_state(0,"raids","combat")
	r.sample_state(2,"raids","combat")
	r.begin_segment({"checkpoint_id":"defense"},0)
	check(r.segment==2 and r.dwell.combat.simulation_s==2,"Restart closes the previous segment before resetting its clock")
	check(r.events[0].mode=="campaign" and r.events[-1].checkpoint_id=="defense" and r.events[-1].segment==2,"Events retain their original provenance across checkpoint changes")
	r.record(0,"raids","combat","bad-values",{"nan":NAN,"node":self,"deep":{"a":{"b":{"c":{"d":1}}}}})
	var bad=r.events[-1].payload
	check(bad.nan==null and bad.node=="[unsupported value]" and r.payload_truncations>0,"Non-JSON and unbounded payloads become visible limited values")
	for i in 100:r.record(i,"raids","combat","shot",{"i":i})
	check(r.events.size()==16 and r.overflow>0 and r.stored_bytes<=Recorder.MAX_BYTES,"Event capacity bounds memory and counts dropped records")
	check(r.write_report("res://../test-results/godot-native/playtest-recorder.json",2),"Explicit report write succeeds")
	var decoded=JSON.parse_string(FileAccess.get_file_as_string("res://../test-results/godot-native/playtest-recorder.json"))
	check(decoded.schema==1 and decoded.overflow==r.overflow and decoded.events.size()==16,"Report preserves schema and overflow")
	var data=MMFAssets.json("res://data/definitions.json");MMFNativeProgression.apply(data)
	var s=MMFSession.new(data);var before=JSON.stringify(s.native_snapshot());var rng=s.rng.state
	r.configure({"run_id":"passive","mode":"synthetic"},true)
	for i in 20:r.sample_state(s.clock,s.story.phase,"travel",{"health":s.health});r.record(s.clock,s.story.phase,"travel","observe",{"scrap":s.inventory.count_item("scrap")})
	check(s.rng.state==rng and JSON.stringify(s.native_snapshot())==before,"Observing does not change gameplay snapshots or RNG")
	var fingerprint=Recorder.source_fingerprint()
	check(fingerprint.length()==64 and fingerprint==Recorder.source_fingerprint(),"Runtime source fingerprint is complete and repeatable")
	var toggled=Recorder.new();toggled.configure({"run_id":"toggle","mode":"campaign","source_hash":fingerprint},true)
	toggled.sample_state(10,"approach","travel")
	toggled.current.wall_ms-=1000
	toggled.set_recording(false,13)
	var paused_total=toggled.snapshot(73).dwell.travel.duplicate();var previous_events=toggled.events.size()
	toggled.start_ticks-=60000000
	toggled.sample_state(73,"approach","travel")
	check(is_equal_approx(paused_total.simulation_s,3) and toggled.events.size()==previous_events,"Disabling accrues the last active dwell once and records no disabled samples")
	toggled.set_recording(true,73);toggled.sample_state(73,"approach","travel")
	var resumed=toggled.snapshot(75)
	check(is_equal_approx(resumed.dwell.travel.simulation_s,5) and resumed.dwell.travel.wall_ms<paused_total.wall_ms+100,"Resuming excludes the disabled minute from both dwell clocks")
	check(toggled.segment==1 and toggled.events[0].segment==0 and toggled.events[-1].segment==1 and toggled.events.size()>previous_events,"Toggling preserves observations and starts a new provenance segment")
	var stopped=toggled.events.size();toggled.set_recording(true,75)
	check(toggled.events.size()==stopped,"Repeated enabled toggle is a no-op")
	toggled.set_recording(false,75);var off_events=toggled.events.size()
	toggled.begin_segment({"mode":"checkpoint","checkpoint_id":"workshop","seed":"playtest-workshop"},0)
	check(toggled.events.size()==off_events and toggled.metadata.checkpoint_id=="workshop","Loading while disabled updates provenance without observations")
	toggled.set_recording(true,0)
	check(toggled.events[-1].mode=="checkpoint" and toggled.events[-1].checkpoint_id=="workshop","Enabling at a loaded checkpoint does not claim campaign provenance")
	print("PLAYTEST_RECORDER ",checks," checks; failures: ",failures)
	quit(0 if failures.is_empty() else 1)
